#!/bin/bash
while read local_ref local_sha remote_ref remote_sha; do
  if [[ "$remote_ref" == "refs/heads/master" ]]; then
    echo "ERROR: Direct push to master is forbidden. Use a PR."
    exit 1
  fi
done
