#!/usr/bin/env bash
# lib/docs/init.sh
# Sphinx Documentation - Project Initialization
#
# Initializes Sphinx in docs/sphinx/ for any project.
# Does not overwrite existing conf.py (idempotent guard).

#######################################
# Update project .gitignore to exclude docs/sphinx/_build/
# Arguments:
#   $1 - project path
# Returns:
#   0 - always
# Example: _update_project_gitignore /path/to/project
#######################################
_update_project_gitignore() {
    local project_path="$1"
    local gitignore="${project_path}/.gitignore"
    local entry="docs/sphinx/_build/"

    if [[ -f "$gitignore" ]]; then
        if grep -qF "$entry" "$gitignore"; then
            return 0
        fi
        echo "" >> "$gitignore"
        echo "# Sphinx build output" >> "$gitignore"
        echo "$entry" >> "$gitignore"
    else
        {
            echo "# Sphinx build output"
            echo "$entry"
        } > "$gitignore"
    fi
    print_info "Added $entry to .gitignore"
}

#######################################
# Generate conf.py for the project
# Arguments:
#   $1 - output path (docs/sphinx/conf.py)
#   $2 - project name
#   $3 - project type (bash|python|node|generic)
# Returns:
#   0 - always
# Example: _generate_conf_py /path/to/docs/sphinx/conf.py myproject bash
#######################################
_generate_conf_py() {
    local conf_path="$1"
    local project_name="$2"
    local project_type="${3:-generic}"

    local api_comment=""
    if [[ "$project_type" == "bash" ]]; then
        api_comment="# API Reference auto-generated from lib/*.sh (bash-parser)"
    elif [[ "$project_type" == "python" ]]; then
        api_comment="# For Python API docs, add 'sphinx-autoapi' to extensions and install it:"
        api_comment="${api_comment}\n# pip install sphinx-autoapi"
    fi

    cat > "$conf_path" <<EOF
# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html
# Generated by: ./iclaude.sh --init-docs

# -- Project information -------------------------------------------------------
project = "${project_name}"
author = "${project_name} contributors"

# -- General configuration -----------------------------------------------------
extensions = [
    "myst_parser",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinxcontrib.mermaid",
]

# sphinx-llms-txt: generates llms.txt and llms-full.txt for AI agents
# Install: pip install sphinx-llms-txt
try:
    import sphinx_llms_txt  # noqa: F401
    extensions.append("sphinx_llms_txt")
except ImportError:
    pass  # Optional — docs build without it

# MyST Parser — use Markdown with full Sphinx capabilities
myst_enable_extensions = [
    "colon_fence",   # ::: blocks as alternative to \`\`\` for directives
    "deflist",       # Definition lists
    "fieldlist",     # Field lists
    "attrs_inline",  # Inline attributes {.class}
]

# File formats
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# Exclude patterns (relative to docs/sphinx/)
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
]

# -- HTML output ---------------------------------------------------------------
html_theme = "furo"
html_title = "${project_name} Documentation"

# Furo theme options
html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

# -- sphinx-llms-txt -----------------------------------------------------------
# AI-first documentation: generates llms.txt and llms-full.txt
# These files allow AI agents to consume documentation efficiently
# See: https://llmstxt.org/
EOF

    if [[ -n "$api_comment" ]]; then
        echo "" >> "$conf_path"
        echo "# ${api_comment#\# }" >> "$conf_path"
    fi
}

#######################################
# Generate index.md for the project, referencing existing docs/*.md
# Arguments:
#   $1 - output path (docs/sphinx/index.md)
#   $2 - project name
#   $3 - project path
# Returns:
#   0 - always
# Example: _generate_index_md /path/to/docs/sphinx/index.md myproject /path/to/project
#######################################
_generate_index_md() {
    local index_path="$1"
    local project_name="$2"
    local project_path="$3"

    # Collect existing docs/*.md files (sorted, exclude index.md itself)
    local docs_dir="${project_path}/docs"
    local toctree_entries=""
    if [[ -d "$docs_dir" ]]; then
        while IFS= read -r -d '' md_file; do
            local basename
            basename=$(basename "$md_file" .md)
            # Skip if it's an index file or starts with underscore
            [[ "$basename" == "index" ]] && continue
            [[ "$basename" == _* ]] && continue
            toctree_entries="${toctree_entries}
../${basename}"
        done < <(find "$docs_dir" -maxdepth 1 -name "*.md" -print0 | sort -z)
    fi

    cat > "$index_path" <<EOF
---
title: ${project_name} Documentation
---

# ${project_name}

```{toctree}
:maxdepth: 1
:caption: Documentation
EOF

    # Add found docs entries
    if [[ -n "$toctree_entries" ]]; then
        echo "$toctree_entries" >> "$index_path"
    fi

    cat >> "$index_path" <<'EOF'
```

```{toctree}
:maxdepth: 2
:caption: API Reference
:hidden:

api-reference/index
```

---

:::{note}
**For AI agents:** This documentation generates `llms.txt` and `llms-full.txt` at build time.
Use them for efficient navigation: `docs/sphinx/_build/html/llms.txt`
:::
EOF
}

#######################################
# Initialize Sphinx documentation in docs/sphinx/ for any project
# Arguments:
#   $1 - project path (default: pwd)
# Returns:
#   0 - Success or already initialized
#   1 - Failed to create directory or generate files
# Example: init_project_docs /path/to/project
#######################################
if ! declare -F init_project_docs &>/dev/null; then
init_project_docs() {
    local project_path
    project_path=$(get_docs_project_dir "${1:-$(pwd)}")
    local sphinx_dir
    sphinx_dir=$(get_docs_sphinx_dir "$project_path")

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Initializing Sphinx Documentation"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    print_info "Project: $project_path"

    # Guard: don't overwrite existing conf.py
    if [[ -f "${sphinx_dir}/conf.py" ]]; then
        print_warning "docs/sphinx/conf.py already exists. Use --build-docs to rebuild."
        echo ""
        echo "  Sphinx dir: $sphinx_dir"
        echo "  To force reinit: remove $sphinx_dir/conf.py first"
        return 0
    fi

    # Create sphinx directory
    if ! mkdir -p "$sphinx_dir"; then
        print_error "Failed to create directory: $sphinx_dir"
        return 1
    fi

    local project_name
    project_name=$(get_docs_project_name "$project_path")
    local project_type
    project_type=$(detect_project_type "$project_path")

    print_info "Project name:  $project_name"
    print_info "Project type:  $project_type"

    # Generate conf.py
    print_info "Generating conf.py..."
    _generate_conf_py "${sphinx_dir}/conf.py" "$project_name" "$project_type"

    # Generate index.md
    print_info "Generating index.md..."
    _generate_index_md "${sphinx_dir}/index.md" "$project_name" "$project_path"

    # Update .gitignore
    _update_project_gitignore "$project_path"

    echo ""
    print_success "Sphinx initialized: $sphinx_dir"
    echo ""
    echo "  conf.py:   ${sphinx_dir}/conf.py"
    echo "  index.md:  ${sphinx_dir}/index.md"
    echo ""
    echo "  Next steps:"
    echo "    ./iclaude.sh --install-docs"
    echo "    ./iclaude.sh --build-docs $project_path"
    echo "    ./iclaude.sh --serve-docs $project_path"
    echo ""

    return 0
}
fi
